name: Generate Next Release Tag
description: Get the latest release tag and generate the next one in the format R-<sequence>-YYYYMMDDHHMMSS

inputs:
  github-token:
    required: true
    description: GitHub token for GitHub CLI access
outputs:
  new-tag:
    description: The new release tag (e.g., R-004-20250702191245)
    value: ${{ steps.generate.outputs.new_tag }}

runs:
  using: "composite"
  steps:
    - name: Get current UTC timestamp
      id: time
      run: echo "timestamp=$(date -u +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Get latest release tag
      id: latest
      run: |
        latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "")
        echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Generate Release Tag
      id: generate-tag
      run: |
        latest="${{ steps.latest.outputs.latest_tag }}"
        if [[ "$latest" =~ ^R-([0-9]+)-[0-9]{14}$ ]]; then
          seq_num=$(echo "$latest" | cut -d'-' -f2)
          new_seq=$(printf "%03d" $((10#$seq_num + 1)))
        else
          echo "⚠️ No valid tag found. Starting from 1."
          new_seq="1"
        fi

        new_tag="Rel-${new_seq}-${{ steps.time.outputs.timestamp }}"
        echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"
      shell: bash
